In [8]:
from sklearn.preprocessing import LabelEncoder
#모듈 로드
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential  #모델 만들기
from tensorflow.keras.layers import Dense, Dropout, Flatten  #레이어 쌓기
from tensorflow.keras.optimizers import SGD, RMSprop, Adam
from tensorflow.keras.losses import sparse_categorical_crossentropy, categorical_crossentropy, binary_crossentropy, mean_squared_error
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.models import load_model

In [2]:
from tensorflow.keras.datasets import boston_housing
(X_data, y_data), (tt_x, tt_y)=boston_housing.load_data()

65536/57026 [==================================] - 0s 0us/step


In [3]:
X_data.shape

(404, 13)

In [4]:
y_data.shape

(404,)

In [7]:
np.unique(y_data) #실제값이 겁나 많으면 일반적으로 회귀문제

array([ 5. ,  6.3,  7. ,  7.2,  7.5,  8.3,  8.4,  8.5,  8.7,  8.8,  9.6,
       10.2, 10.4, 10.5, 10.8, 10.9, 11. , 11.3, 11.5, 11.7, 11.8, 11.9,
       12.1, 12.3, 12.5, 12.6, 12.7, 12.8, 13.1, 13.2, 13.3, 13.4, 13.5,
       13.6, 13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.8,
       14.9, 15. , 15.1, 15.2, 15.3, 15.6, 15.7, 16. , 16.1, 16.2, 16.3,
       16.4, 16.5, 16.6, 16.7, 16.8, 17. , 17.1, 17.2, 17.3, 17.4, 17.5,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.7, 18.8,
       18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9,
       20. , 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 21. , 21.1,
       21.2, 21.4, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3, 22.4,
       22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4, 23.5,
       23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.3, 24.4, 24.5, 24.6, 24.7,
       24.8, 25. , 25.1, 25.2, 25.3, 26.2, 26.4, 26.5, 26.6, 27.1, 27.5,
       27.9, 28. , 28.2, 28.5, 28.6, 28.7, 29. , 29

In [22]:
m = Sequential()

m.add(Dense(26,activation='relu',input_shape=(13,)))
m.add(Dense(52, activation = 'relu'))
m.add(Dense(1)) #회귀 문제는 논리 연산이 필요한 분류 문제와 달리 회귀값만 나타나면 되므로 활성화함수가 필요 없다.
#분류 문제는 회귀값을 sigmoid, softmax 등의 출렴함수를 거쳐야 값이 나온다.
m.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 26)                364       
                                                                 
 dense_10 (Dense)            (None, 52)                1404      
                                                                 
 dense_11 (Dense)            (None, 1)                 53        
                                                                 
Total params: 1,821
Trainable params: 1,821
Non-trainable params: 0
_________________________________________________________________


In [23]:
m.compile(loss = 'mse', metrics=['mae']) #학습 방법: mse, 평가:mae(평균 절대값 오차)

In [25]:
m.fit(X_data, y_data, epochs = 1000)

Epoch 1/1000
13/13 [==============================] - 0s 3ms/step - loss: 34.8753 - mae: 4.4159
Epoch 2/1000
13/13 [==============================] - 0s 2ms/step - loss: 36.4751 - mae: 4.3701
Epoch 3/1000
13/13 [==============================] - 0s 3ms/step - loss: 36.2204 - mae: 4.4530
Epoch 4/1000
13/13 [==============================] - 0s 2ms/step - loss: 39.6424 - mae: 4.6497
Epoch 5/1000
13/13 [==============================] - 0s 2ms/step - loss: 30.8904 - mae: 3.9360
Epoch 6/1000
13/13 [==============================] - 0s 2ms/step - loss: 33.5159 - mae: 4.3412
Epoch 7/1000
13/13 [==============================] - 0s 2ms/step - loss: 35.8471 - mae: 4.4476
Epoch 8/1000
13/13 [==============================] - 0s 2ms/step - loss: 37.1448 - mae: 4.4273
Epoch 9/1000
13/13 [==============================] - 0s 2ms/step - loss: 34.6701 - mae: 4.1700
Epoch 10/1000
13/13 [==============================] - 0s 3ms/step - loss: 38.8002 - mae: 4.3283
Epoch 11/1000
13/13 [==================

In [26]:
m.predict(X_data[:5])

array([[18.057798],
       [40.68614 ],
       [48.584652],
       [22.00403 ],
       [19.487957]], dtype=float32)

In [27]:
y_data[:5]

array([15.2, 42.3, 50. , 21.1, 17.7])