In [6]:
from sklearn.datasets import fetch_20newsgroups
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

In [7]:
w_data = fetch_20newsgroups()
w_data.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [8]:
X_data = w_data.data
y_data = w_data.target

In [9]:
import numpy as np 
np.unique(y_data) #다중 클래스 분류

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
all_data = pd.DataFrame()
all_data['X'] = X_data
all_data['y'] = y_data
all_data

X   y
0      From: lerxst@wam.umd.edu (where's my thing)\nS...   7
1      From: guykuo@carson.u.washington.edu (Guy Kuo)...   4
2      From: twillis@ec.ecn.purdue.edu (Thomas E Will...   4
3      From: jgreen@amber (Joe Green)\nSubject: Re: W...   1
4      From: jcm@head-cfa.harvard.edu (Jonathan McDow...  14
...                                                  ...  ..
11309  From: jim.zisfein@factory.com (Jim Zisfein) \n...  13
11310  From: ebodin@pearl.tufts.edu\nSubject: Screen ...   4
11311  From: westes@netcom.com (Will Estes)\nSubject:...   3
11312  From: steve@hcrlgw (Steven Collins)\nSubject: ...   1
11313  From: gunning@cco.caltech.edu (Kevin J. Gunnin...   8

[11314 rows x 2 columns]

In [11]:
n_l = []
for i in X_data:
    n = len(i)
    n_l.append(n)
max(n_l), min(n_l)

(75154, 125)

In [12]:
tk = Tokenizer(num_words=10000) #차원을 정함.
tk.fit_on_texts(X_data)
t_x_data = tk.texts_to_matrix(X_data)
t_x_data.shape

(11314, 10000)

In [15]:
t_x_data

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
t1_x_data = tk.texts_to_matrix(X_data, mode='count')
t1_x_data

array([[ 0.,  6.,  2., ...,  0.,  0.,  0.],
       [ 0.,  4.,  1., ...,  0.,  0.,  0.],
       [ 0., 21.,  6., ...,  0.,  0.,  0.],
       ...,
       [ 0., 12.,  1., ...,  0.,  0.,  0.],
       [ 0.,  3.,  2., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [14]:
t2_x_data = tk.texts_to_matrix(X_data, mode='tfidf')
t2_x_data

array([[0.        , 2.03303026, 1.26800369, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.73776026, 0.74890341, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 2.94532413, 2.09075818, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 2.53779767, 0.74890341, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.52826285, 1.26800369, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [16]:
X_data1 = t_x_data
X_data2 = t1_x_data
X_data3 = t2_x_data

In [17]:
Y_data = to_categorical(y_data)

In [18]:
len(X_data1),len(X_data2),len(X_data3),len(Y_data)

(11314, 11314, 11314, 11314)

In [19]:
from sklearn.model_selection import train_test_split
t_x1, tt_x1, t_y1, tt_y1 = train_test_split(X_data1, Y_data, random_state=1) #단어 유무 특징 갖는 data
t_x2, tt_x2, t_y2, tt_y2 = train_test_split(X_data2, Y_data, random_state=1) #단어 빈도수 data
t_x3, tt_x3, t_y3, tt_y3 = train_test_split(X_data3, Y_data, random_state=1) #tdidf 단어 가중치 data

모델 생성

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [21]:
m = Sequential()
m.add(Dense(256,input_shape=(10000,), activation='relu'))
m.add(Dropout(0.3))
m.add(Dense(128, activation='relu'))
m.add(Dropout(0.3))
m.add(Dense(20, activation='softmax'))
m.compile(optimizer='adam',loss='categorical_crossentropy', metrics = 'accuracy')
hy = m.fit(t_x1, t_y1, epochs=10, validation_data=[tt_x1, tt_y1])

Epoch 1/10
266/266 [==============================] - 7s 22ms/step - loss: 1.3979 - accuracy: 0.6131 - val_loss: 0.4893 - val_accuracy: 0.8706
Epoch 2/10
266/266 [==============================] - 6s 21ms/step - loss: 0.2884 - accuracy: 0.9267 - val_loss: 0.3601 - val_accuracy: 0.8968
Epoch 3/10
266/266 [==============================] - 6s 21ms/step - loss: 0.1136 - accuracy: 0.9770 - val_loss: 0.4310 - val_accuracy: 0.8795
Epoch 4/10
266/266 [==============================] - 6s 21ms/step - loss: 0.0593 - accuracy: 0.9874 - val_loss: 0.4001 - val_accuracy: 0.8954
Epoch 5/10
266/266 [==============================] - 7s 26ms/step - loss: 0.0440 - accuracy: 0.9923 - val_loss: 0.4192 - val_accuracy: 0.8894
Epoch 6/10
266/266 [==============================] - 6s 22ms/step - loss: 0.0382 - accuracy: 0.9940 - val_loss: 0.4274 - val_accuracy: 0.8957
Epoch 7/10
266/266 [==============================] - 6s 21ms/step - loss: 0.0222 - accuracy: 0.9969 - val_loss: 0.4465 - val_accuracy: 0.8961

In [22]:
type(t_x1), type(t_y1)

(numpy.ndarray, numpy.ndarray)