In [22]:
import numpy as np
#y = wx + b
def AND(x1, x2):
    w1, w2 = [1,1] #초기 가중치는 임의의 값 지정
    X = np.array([x1, x2]) #x가 두개 들어와서 넘파이 배열로 묶어줌
    W = np.array([w1, w2]) #x가 두개니까 w도 두개
    b = -1.5 #바이어스도 임의의 값 지정
    t = np.sum(W*X) + b 
    if t <= 0: #결과값이 음수면
        return 0 #0 리턴
    else:
        return 1 #양수면 1리턴

def OR(x1, x2):
    w1, w2 = [1,1] #초기 가중치는 임의의 값 지정
    X = np.array([x1, x2]) #x가 두개 들어와서 넘파이 배열로 묶어줌
    W = np.array([w1, w2]) #x가 두개니까 w도 두개
    b = -0.5 #바이어스도 임의의 값 지정
    t = np.sum(W*X) + b 
    if t <= 0: #결과값이 음수면
        return 0 #0 리턴
    else:
        return 1

def NAND(x1, x2):
    w1, w2 = [1,1] #초기 가중치는 임의의 값 지정
    X = np.array([x1, x2]) #x가 두개 들어와서 넘파이 배열로 묶어줌
    W = np.array([w1, w2]) #x가 두개니까 w도 두개
    b = -1.5
    t = np.sum(W*X) + b 
    if t <= 0: 
        return 1
    else:
        return 0 

def XOR(x1, x2):
    o1 = NAND(x1, x2)
    o2 = OR(x1, x2)
    return AND(o1, o2)


print('AND')
print(AND(0,0))
print(AND(0,1))
print(AND(1,0))
print(AND(1,1))

print('OR')
print(OR(0,0))
print(OR(0,1))
print(OR(1,0))
print(OR(1,1))

print('NAND')
print(NAND(0,0))
print(NAND(0,1))
print(NAND(1,0))
print(NAND(1,1))


print('XOR')
print(XOR(0,0))
print(XOR(0,1))
print(XOR(1,0))
print(XOR(1,1))

AND
0
0
0
1
OR
0
1
1
1
NAND
1
1
1
0
XOR
0
1
1
0


In [31]:
from sklearn.linear_model import LogisticRegression, Perceptron
#AND연산
X = [[0,0],[0,1],[1,0],[1,1]]
y = [0,1,1,0]
k = LogisticRegression()
k.fit(X,y)
print(k.coef_, k.intercept_)
p = Perceptron()
p.fit(X, y)
print(p.coef_, p.intercept_)

[[0. 0.]] [0.]
[[0. 0.]] [0.]


In [30]:

def AND(x1, x2):
    w1, w2 = [1,1] #초기 가중치는 임의의 값 지정
    X = np.array([x1, x2]) #x가 두개 들어와서 넘파이 배열로 묶어줌
    W = np.array([2,2]) #x가 두개니까 w도 두개
    b = -1 #바이어스도 임의의 값 지정
    t = np.sum(W*X) + b 
    if t <= 0: #결과값이 음수면
        return 0 #0 리턴
    else:
        return 1 #양수면 1리턴

print('AND')
print(AND(0,0))
print(AND(0,1))
print(AND(1,0))
print(AND(1,1))


AND
0
1
1
1


In [ ]:
import numpy as np

# 시그모이드 함수
def actf(x):
    return 1 / (1 + np.exp(-x))

# 시그모이드 함수의 미분값
def actf_deriv(x):
    return x * (1 - x)

# XOR 연산을 위한 4행*2열의 입력 행렬
# 마지막 열은 바이어스를 나타낸다.
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

# XOR 연산을 위한 4행*1열의 목표 행렬
y = np.array([[0], [1], [1], [0]])

np.random.seed(5)

inputs = 3  # 입력층의 노드 개수
hiddens = 6  # 은닉층의 노드 개수
outputs = 1  # 출력층의 노드 개수

# 가중치를 –1.0에서 1.0 사이의 난수로 초기화한다.
weight0 = 2 * np.random.random((inputs, hiddens)) - 1
weight1 = 2 * np.random.random((hiddens, outputs)) - 1

# 반복한다.
for i in range(10000):
    # 순방향 계산
    layer0 = X  # 입력을 layer0에 대입한다.
    net1 = np.dot(layer0, weight0)  # 행렬의 곱을 계산한다.
    layer1 = actf(net1)  # 활성화 함수를 적용한다.
    layer1[:, -1] = 1.0  # 마지막 열은 바이어스를 나타낸다. 1.0으로 만든다.
    net2 = np.dot(layer1, weight1)  # 행렬의 곱을 계산한다.
    layer2 = actf(net2)  # 활성화 함수를 적용한다.

    # 출력층에서의 오차를 계산한다.
    layer2_error = layer2 - y

    # 출력층에서의 델타값을 계산한다.
    layer2_delta = layer2_error * actf_deriv(layer2) #결과값이 입력으로 바뀌어서 활성화함수 미분

    # 은닉층에서의 오차를 계산한다.
    # 여기서 T는 행렬의 전치를 의미한다.
    # 역방향으로 오차를 전파할 때는 반대방향이므로 행렬이 전치되어야 한다.
    layer1_error = np.dot(layer2_delta, weight1.T)

    # 은닉층에서의 델타를 계산한다.
    layer1_delta = layer1_error * actf_deriv(layer1)

    # 은닉층->출력층을 연결하는 가중치를 수정한다.
    weight1 += -0.2 * np.dot(layer1.T, layer2_delta)

    # 입력층->은닉층을 연결하는 가중치를 수정한다.
    weight0 += -0.2 * np.dot(layer0.T, layer1_delta)
print(layer2)  # 현재 출력층의 값을 출력한다.
print(layer2>0.5)

In [34]:
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([[0], [1], [1], [0]])
X.shape, y.shape

((4, 3), (4, 1))

In [45]:
#XOR
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten

m = Sequential()
m.add(Flatten(input_shape = (3,))) #입력 뉴런의 개수는 입력 데이터의 피처 개수
m.add(Dense(6,activation= 'sigmoid'))
m.add(Dense(1,activation= 'sigmoid'))


#m.add(Dense(6,activation= 'sigmoid',input_shape = (3,)))
#m.add(Dense(1,activation= 'sigmoid'))

m.summary()
m.compile(loss='binary_crossentropy', metrics = 'accuracy')

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 3)                 0         
                                                                 
 dense_6 (Dense)             (None, 6)                 24        
                                                                 
 dense_7 (Dense)             (None, 1)                 7         
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [42]:
m.fit(X,y,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7314 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.7304 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.7295 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7287 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7279 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.7271 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.7263 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 22ms/step - loss: 0.7256 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.7250 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.7243 - accuracy: 0.5000
Epoch 11/1

In [43]:
m.predict(np.array([[0,0,1]]))

array([[0.4040988]], dtype=float32)