In [1]:
! pip install kss konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 42.4 MB 1.1 MB/s 
     |████████████████████████████████| 19.4 MB 472 kB/s 
     |████████████████████████████████| 131 kB 52.5 MB/s 
     |████████████████████████████████| 453 kB 34.8 MB/s 
  Created wheel for kss: filename=kss-3.4.3-py3-none-any.whl size=42448068 sha256=d20502482ae5443295f561b78c9820b1c482905bc283c3e10cca3d2c65b3331e
  Stored in directory: /root/.cache/pip/wheels/10/df/7d/0d0a58843aa7d267687671cf57274080bcfe8f79d59ed8f399
Successfully built kss


In [5]:
from tensorflow import keras
(x_train, _), _ = keras.datasets.imdb.load_data()
word_index = keras.datasets.imdb.get_word_index()
inverted_word_index = dict((i, word) for (word, i) in word_index.items())
decoded_sequence = " ".join(inverted_word_index[i] for i in x_train[0])
decoded_sequence,x_train[0]

1654784/1641221 [==============================] - 0s 0us/step


("the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of gilmore's br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but w

In [2]:
import nltk, kss, konlpy #영어, , 한국어

In [4]:
nltk.__version__, konlpy.__version__

('3.7', '0.6.0')

In [6]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer

In [9]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [10]:
d ='the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every'

In [ ]:
word_tokenize(d)

In [ ]:
WordPunctTokenizer().tokenize(d)

In [ ]:
text_to_word_sequence(d)

In [ ]:
from nltk.tokenize import TreebankWordTokenizer
TreebankWordTokenizer().tokenize(d)

In [16]:
d = "Don't be fooled by the dark sounding name, hom-data Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."

In [17]:
word_tokenize(d)

['Do',
 "n't",
 'be',
 'fooled',
 'by',
 'the',
 'dark',
 'sounding',
 'name',
 ',',
 'hom-data',
 'Mr.',
 'Jone',
 "'s",
 'Orphanage',
 'is',
 'as',
 'cheery',
 'as',
 'cheery',
 'goes',
 'for',
 'a',
 'pastry',
 'shop',
 '.']

In [18]:
WordPunctTokenizer().tokenize(d) #같은 패키지에서 가져온 토크나이즈들인데 결과가 다르다.

['Don',
 "'",
 't',
 'be',
 'fooled',
 'by',
 'the',
 'dark',
 'sounding',
 'name',
 ',',
 'hom',
 '-',
 'data',
 'Mr',
 '.',
 'Jone',
 "'",
 's',
 'Orphanage',
 'is',
 'as',
 'cheery',
 'as',
 'cheery',
 'goes',
 'for',
 'a',
 'pastry',
 'shop',
 '.']

In [19]:
text_to_word_sequence(d)

["don't",
 'be',
 'fooled',
 'by',
 'the',
 'dark',
 'sounding',
 'name',
 'hom',
 'data',
 'mr',
 "jone's",
 'orphanage',
 'is',
 'as',
 'cheery',
 'as',
 'cheery',
 'goes',
 'for',
 'a',
 'pastry',
 'shop']

In [20]:
TreebankWordTokenizer().tokenize(d)

['Do',
 "n't",
 'be',
 'fooled',
 'by',
 'the',
 'dark',
 'sounding',
 'name',
 ',',
 'hom-data',
 'Mr.',
 'Jone',
 "'s",
 'Orphanage',
 'is',
 'as',
 'cheery',
 'as',
 'cheery',
 'goes',
 'for',
 'a',
 'pastry',
 'shop',
 '.']

In [22]:
from nltk.tokenize import sent_tokenize #문장 토큰

In [24]:
d_k = '안녕하세용. 반갑습니당. 집에 가고 싶습니다. 배가 고프기도 합니다. 제가 너무 불쌍해지는군요.'

In [23]:
d2 = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
sent_tokenize(d2)

['His barber kept his word.',
 'But keeping such a huge secret to himself was driving him crazy.',
 'Finally, the barber went up a mountain and almost to the edge of a cliff.',
 'He dug a hole in the midst of some reeds.',
 'He looked about, to make sure no one was near.']

In [26]:
sent_tokenize(d_k)
#한국어든 영어든 alpha로 판단해서 똑같이 토큰화가 된다.

['안녕하세용.', '반갑습니당.', '집에 가고 싶습니다.', '배가 고프기도 합니다.', '제가 너무 불쌍해지는군요.']

In [40]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag #영어
from konlpy.tag import Okt #한국어 형태소 분석기
from konlpy.tag import Kkma #학습되어있는 전처리기. 

In [31]:
e_d = "Don't be fooled by the dark sounding name, hom-data Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."

In [30]:
k_d = '너무 더워서 에어컨을 틀었는데 너무 추워서 패딩을 입었다. 너무 또 더워서 냉면을 먹었다.'

In [33]:
n_t = word_tokenize(e_d)

In [34]:
pos_tag(n_t)
#단어마다 역할을 태깅해줌 (품사)

[('Do', 'VBP'),
 ("n't", 'RB'),
 ('be', 'VB'),
 ('fooled', 'VBN'),
 ('by', 'IN'),
 ('the', 'DT'),
 ('dark', 'NN'),
 ('sounding', 'VBG'),
 ('name', 'NN'),
 (',', ','),
 ('hom-data', 'JJ'),
 ('Mr.', 'NNP'),
 ('Jone', 'NNP'),
 ("'s", 'POS'),
 ('Orphanage', 'NN'),
 ('is', 'VBZ'),
 ('as', 'RB'),
 ('cheery', 'JJ'),
 ('as', 'IN'),
 ('cheery', 'NN'),
 ('goes', 'VBZ'),
 ('for', 'IN'),
 ('a', 'DT'),
 ('pastry', 'NN'),
 ('shop', 'NN'),
 ('.', '.')]

In [35]:
k_n = Okt() #클래스임

In [36]:
k_n.morphs(k_d) #단어들만 출력

['너무',
 '더워서',
 '에어컨',
 '을',
 '틀었는데',
 '너무',
 '추워서',
 '패딩',
 '을',
 '입었다',
 '.',
 '너무',
 '또',
 '더워서',
 '냉면',
 '을',
 '먹었다',
 '.']

In [37]:
k_n.pos(k_d) #품사

[('너무', 'Adverb'),
 ('더워서', 'Adjective'),
 ('에어컨', 'Noun'),
 ('을', 'Josa'),
 ('틀었는데', 'Verb'),
 ('너무', 'Adverb'),
 ('추워서', 'Adjective'),
 ('패딩', 'Noun'),
 ('을', 'Josa'),
 ('입었다', 'Verb'),
 ('.', 'Punctuation'),
 ('너무', 'Adverb'),
 ('또', 'Noun'),
 ('더워서', 'Adjective'),
 ('냉면', 'Noun'),
 ('을', 'Josa'),
 ('먹었다', 'Verb'),
 ('.', 'Punctuation')]

In [38]:
k_n.nouns(k_d)#명사만 뽑음

['에어컨', '패딩', '또', '냉면']

In [41]:
k_n2 = Kkma()
k_n2.morphs(k_d), k_n2.pos(k_d), k_n2.nouns(k_d)

(['너무',
  '덥',
  '어서',
  '에어컨',
  '을',
  '튿',
  '었',
  '는데',
  '너무',
  '춥',
  '어서',
  '패딩',
  '을',
  '입',
  '었',
  '다',
  '.',
  '너무',
  '또',
  '덥',
  '어서',
  '냉면',
  '을',
  '먹',
  '었',
  '다',
  '.'],
 [('너무', 'MAG'),
  ('덥', 'VA'),
  ('어서', 'ECD'),
  ('에어컨', 'NNG'),
  ('을', 'JKO'),
  ('튿', 'VV'),
  ('었', 'EPT'),
  ('는데', 'ECD'),
  ('너무', 'MAG'),
  ('춥', 'VA'),
  ('어서', 'ECD'),
  ('패딩', 'NNG'),
  ('을', 'JKO'),
  ('입', 'VV'),
  ('었', 'EPT'),
  ('다', 'EFN'),
  ('.', 'SF'),
  ('너무', 'MAG'),
  ('또', 'MAG'),
  ('덥', 'VA'),
  ('어서', 'ECD'),
  ('냉면', 'NNG'),
  ('을', 'JKO'),
  ('먹', 'VV'),
  ('었', 'EPT'),
  ('다', 'EFN'),
  ('.', 'SF')],
 ['에어컨', '패딩', '냉면'])

In [44]:
data = '오늘은 내용이 쉽지는 않군요 그런데 원래도 그랬고 배고파요. 집에 가고파요'

In [45]:
stopword = '은 는 이 가 요 배고파요'.split()
stopword

['은', '는', '이', '가', '요', '배고파요']

In [46]:
okt = Okt()
t_d = okt.morphs(data)
t_d

['오늘',
 '은',
 '내용',
 '이',
 '쉽지는',
 '않군요',
 '그런데',
 '원래',
 '도',
 '그랬고',
 '배고파요',
 '.',
 '집',
 '에',
 '가고',
 '파',
 '요']

In [47]:
end_d = [i for i in t_d if not i in stopword]
#불용어를 걸러버림

In [48]:
end_d

['오늘', '내용', '쉽지는', '않군요', '그런데', '원래', '도', '그랬고', '.', '집', '에', '가고', '파']

In [101]:
import re #정규표현식 패키지.
r = re.compile('d.t')
r.search('datadatadata') #serch는 같은 문자열을 찾음. 정규표현식 포함해서

<re.Match object; span=(0, 3), match='dat'>

In [60]:
r = re.compile('d?t')
r.search('cat') # 직접 입력된 내용을 찾는다.
#r이라는 변수에 t 앞에 d가 있어도 되고 없어도 된다는 조건(문자)을 집어넣음. 
#그 중 search라는 메소드는 r에 담긴 문자가 매개변수에 포함되어 있는지 확인하고 그 위치를 알려주는 듯?

<re.Match object; span=(2, 3), match='t'>

In [66]:
r = re.compile('d+')
r.search('dsadsaf')

<re.Match object; span=(0, 1), match='d'>

In [70]:
r = re.compile('^ds')
r.search('dssss')

<re.Match object; span=(0, 2), match='ds'>

In [76]:
import pandas as pd

data = ' ?'
r = re.compile('^ ')
if r.search(data):
    data = data[1:]

data

'?'

In [ ]:
#df['key'] = df.key.str.replace('^ ', data[1:])
#판다스 내 str 메소드를 쓰면 알아서 정규표현식을 인식한다.

In [78]:
r = re.compile('d+t')
r.search('dtsadsdtaf')

<re.Match object; span=(0, 2), match='dt'>

In [82]:
r = re.compile('d+t$') #d라는 문자가 최소 한 번 인식되며 바로 뒤에 t가 있고 그 문자가 가장 뒤에 있어야 매치한다.
r.search('dtsadsdtafdt')

<re.Match object; span=(10, 12), match='dt'>

In [98]:
import pandas as pd
k = pd.DataFrame(['a data', 'ada ta','adata', '  data'], columns=['data'])
k

data
0  a data
1  ada ta
2   adata
3    data

In [99]:
k.data.str.replace('^a','')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


0      data
1     da ta
2      data
3      data
Name: data, dtype: object

In [100]:
'^ + data'.replace('^ +','')

' data'

In [105]:
r= re.compile('asd{2}k') #숫자만큼 반복
r.search('fsdafsasddk')

<re.Match object; span=(6, 11), match='asddk'>

In [110]:
r = re.compile('asd{2,}k') #숫자 이상만큼 반복, {a,b} - a이상 b이하만큼 반복
r.search('asdddddk')

<re.Match object; span=(0, 8), match='asdddddk'>

[ ] - 괄호 안의 문자 유무, [-]범위




In [114]:
r= re.compile('[abc]')
r.search('bcaqe')

<re.Match object; span=(0, 1), match='b'>

In [115]:
r= re.compile('[^a-z1A-z]')
r.searcj

In [ ]:
r re.compile('\d,'aoke[])

정수 인코딩

In [117]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [118]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [122]:
#문장토큰화
tk_d = sent_tokenize(text)
tk_d

['A barber is a person.',
 'a barber is good person.',
 'a barber is huge person.',
 'he Knew A Secret!',
 'The Secret He Kept is huge secret.',
 'Huge secret.',
 'His barber kept his word.',
 'a barber kept his word.',
 'His barber kept his secret.',
 'But keeping and keeping such a huge secret to himself was driving the barber crazy.',
 'the barber went up a huge mountain.']

In [124]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
words = {}
t_data = []
sw = set(stopwords.words('english'))
sw

In [128]:
for s in tk_d:
    words_info = word_tokenize(s)
    l = []
    for word in words_info:
        lower_word = word.lower()
        if lower_word not in sw:
            if len(lower_word) > 2: #두글자 이하는 큰 의미가 없는 단어이기 때문에 걸러주려 한다.
                l.append(lower_word)
                if lower_word not in words:
                    words[lower_word] = 0
                words[lower_word] += 1  #단어모음집 word 딕셔너리에 단어의 수를 늘려준다.
    t_data.append(l)
t_data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [129]:
words #단어의 빈도수

{'barber': 8,
 'crazy': 1,
 'driving': 1,
 'good': 1,
 'huge': 5,
 'keeping': 2,
 'kept': 4,
 'knew': 1,
 'mountain': 1,
 'person': 3,
 'secret': 6,
 'went': 1,
 'word': 2}

In [134]:
sorted_words = sorted(words.items(), key = lambda x: x[1], reverse = True)
sorted_words

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [139]:
word_idx = {}
i = 0
for word, num in sorted_words:
    if num > 1:
        i += 1
        word_idx[word] = i
word_idx #vocabrary가 만들어진 것.

{'barber': 1,
 'huge': 3,
 'keeping': 7,
 'kept': 4,
 'person': 5,
 'secret': 2,
 'word': 6}

In [140]:
remain_words = 4 #4 단어만 살릴 것
remove_data = [word for word, i in word_idx.items() if i > remain_words]
for i in remove_data:
    del word_idx[i]
word_idx

{'barber': 1, 'huge': 3, 'kept': 4, 'secret': 2}

In [141]:
#out of vocabrary
#oov는 아예 없애든가 쓰든가 한다.
#oov를 단어취급할거면 단어로 등록. 그럼 가장 큰 숫자값으로 줄 것이다.(가장 큰 숫자가 제일 쓸모없으니)
#oov를 사용할거면 단어 인덱스를 잊지 말아야 한다.
word_idx['oov'] = len(word_idx) + 1
word_idx

{'barber': 1, 'huge': 3, 'kept': 4, 'oov': 5, 'secret': 2}

In [142]:
t_data


[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [143]:
#입력되어있는 단어를 숫자로 바꾼다.
ec_data = [] #인코딩 데이터
for sentence in t_data:
    ec_d = []
    for word in sentence:
        try:  #빈도수가 적은 단어를 제거해줘서 존재하지 않은 단어를 부르려고 할 때 예외처리를 해주려 한다.
            ec_d.append(word_idx[word])
        except KeyError:
            ec_d.append(word_idx['oov']) #사라졌던 단어들은 모두 oov로 취급
    ec_data.append(ec_d)

ec_data

[[1, 5],
 [1, 5, 5],
 [1, 3, 5],
 [5, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 5],
 [1, 4, 5],
 [1, 4, 2],
 [5, 5, 3, 2, 5, 1, 5],
 [1, 5, 3, 5]]

Counter 기반 정수 인코딩

In [144]:
from collections import Counter
#토큰화가 끝난 데이터.
#코퍼스 -> 문장 -> 단어
t_data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [145]:
단어모두모음 = sum(t_data, [])
단어모두모음

['barber',
 'person',
 'barber',
 'good',
 'person',
 'barber',
 'huge',
 'person',
 'knew',
 'secret',
 'secret',
 'kept',
 'huge',
 'secret',
 'huge',
 'secret',
 'barber',
 'kept',
 'word',
 'barber',
 'kept',
 'word',
 'barber',
 'kept',
 'secret',
 'keeping',
 'keeping',
 'huge',
 'secret',
 'driving',
 'barber',
 'crazy',
 'barber',
 'went',
 'huge',
 'mountain']

In [146]:
end_단어_모음 = Counter(단어모두모음)
end_단어_모음

Counter({'barber': 8,
         'crazy': 1,
         'driving': 1,
         'good': 1,
         'huge': 5,
         'keeping': 2,
         'kept': 4,
         'knew': 1,
         'mountain': 1,
         'person': 3,
         'secret': 6,
         'went': 1,
         'word': 2})

In [147]:
빈도별_단어 = end_단어_모음.most_common(remain_words)
빈도별_단어

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4)]

In [148]:
단어인덱스2 = {}
i=0
for 단어, 빈도수 in 빈도별_단어:
    i += 1
    단어인덱스2[단어] = i
단어인덱스2

{'barber': 1, 'huge': 3, 'kept': 4, 'secret': 2}

In [149]:
단어인덱스2['oov'] = len(단어인덱스2) + 1
단어인덱스2

{'barber': 1, 'huge': 3, 'kept': 4, 'oov': 5, 'secret': 2}

In [150]:
#입력되어있는 단어를 숫자로 바꾼다.
ec_data2 = [] #인코딩 데이터
for sentence in t_data:
    ec_d = []
    for word in sentence:
        try:  #빈도수가 적은 단어를 제거해줘서 존재하지 않은 단어를 부르려고 할 때 예외처리를 해주려 한다.
            ec_d.append(단어인덱스2[word])
        except KeyError:
            ec_d.append(단어인덱스2['oov']) #사라졌던 단어들은 모두 oov로 취급
    ec_data2.append(ec_d)

ec_data2

[[1, 5],
 [1, 5, 5],
 [1, 3, 5],
 [5, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 5],
 [1, 4, 5],
 [1, 4, 2],
 [5, 5, 3, 2, 5, 1, 5],
 [1, 5, 3, 5]]

영어 nltk 정수인코딩

In [152]:
from nltk import FreqDist
import numpy as np

In [153]:
#토큰화된 데이터
t_data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [158]:
단어_모음집 = FreqDist(np.hstack(t_data))
단어_모음집

FreqDist({'barber': 8,
          'crazy': 1,
          'driving': 1,
          'good': 1,
          'huge': 5,
          'keeping': 2,
          'kept': 4,
          'knew': 1,
          'mountain': 1,
          'person': 3,
          'secret': 6,
          'went': 1,
          'word': 2})

In [159]:
결과_단어_모음집 = 단어_모음집.most_common(remain_words)
결과_단어_모음집

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4)]

데이터 전처리

In [160]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [161]:
ck_t = Tokenizer()
ck_t.fit_on_texts(t_data)
print(ck_t.word_index)
print(ck_t.word_counts)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [162]:
tr_data = ck_t.texts_to_sequences(t_data)
tr_data

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [165]:
remain_words

4

In [ ]:
'''Tokenizer()
num_words=None, 
filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', 없앨 문자
lower=True, 소문자
split=' ', 자를 것 기준
char_level=False, 
oov_token=None, oov를 쓸 것인가
document_count=0'''

In [169]:
test=Tokenizer(num_words=remain_words+2,oov_token='oov') #0의 값은 무조건 배제된 oov가 차지, oov_token을 활성화하면 그것이 1로 고정된다.
test.fit_on_texts(t_data)
test.texts_to_sequences(t_data)

[[2, 1],
 [2, 1, 1],
 [2, 4, 1],
 [1, 3],
 [3, 5, 4, 3],
 [4, 3],
 [2, 5, 1],
 [2, 5, 1],
 [2, 5, 3],
 [1, 1, 4, 3, 1, 2, 1],
 [2, 1, 4, 1]]

In [170]:
t_data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [171]:
test.word_index,test.word_counts

({'barber': 2,
  'crazy': 12,
  'driving': 11,
  'good': 9,
  'huge': 4,
  'keeping': 8,
  'kept': 5,
  'knew': 10,
  'mountain': 14,
  'oov': 1,
  'person': 6,
  'secret': 3,
  'went': 13,
  'word': 7},
 OrderedDict([('barber', 8),
              ('person', 3),
              ('good', 1),
              ('huge', 5),
              ('knew', 1),
              ('secret', 6),
              ('kept', 4),
              ('word', 2),
              ('keeping', 2),
              ('driving', 1),
              ('crazy', 1),
              ('went', 1),
              ('mountain', 1)]))

케라스 전처리기 이용해서 정리

데이터 수집(코퍼스 수집)

In [172]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

토큰화

In [173]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [174]:
#문장토큰화
tk_d = sent_tokenize(text)
nltk.download('stopwords')
words = {}
t_data = []
sw = set(stopwords.words('english'))
for s in tk_d:
    words_info = word_tokenize(s)
    l = []
    for word in words_info:
        lower_word = word.lower()
        if lower_word not in sw:
            if len(lower_word) > 2: #두글자 이하는 큰 의미가 없는 단어이기 때문에 걸러주려 한다.
                l.append(lower_word)
                if lower_word not in words:
                    words[lower_word] = 0
                words[lower_word] += 1  #단어모음집 word 딕셔너리에 단어의 수를 늘려준다.
    t_data.append(l)
t_data

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

정수 인코딩

In [175]:
from tensorflow.keras.preprocessing.text import Tokenizer
tk = Tokenizer()
tk.fit_on_texts(t_data)
ec_data = tk.texts_to_sequences(t_data)
ec_data

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

패딩

In [178]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
end_data = pad_sequences(ec_data)
end_data

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [179]:
end_data = pad_sequences(ec_data, padding='post') # 기본값은 뒤쪽. 데이터를 어디로 채울 것인지 정함
end_data

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [180]:
end_data = pad_sequences(ec_data,padding='post', maxlen=4) #잘릴 때는 앞에서부터. 걍 채우든 지우든 앞에서부터라고 생각하면 될듯
end_data

array([[ 1,  5,  0,  0],
       [ 1,  8,  5,  0],
       [ 1,  3,  5,  0],
       [ 9,  2,  0,  0],
       [ 2,  4,  3,  2],
       [ 3,  2,  0,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  2,  0],
       [ 2, 10,  1, 11],
       [ 1, 12,  3, 13]], dtype=int32)

In [181]:
end_data = pad_sequences(ec_data,padding='post', maxlen=4, truncating='post') 
end_data

array([[ 1,  5,  0,  0],
       [ 1,  8,  5,  0],
       [ 1,  3,  5,  0],
       [ 9,  2,  0,  0],
       [ 2,  4,  3,  2],
       [ 3,  2,  0,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  2,  0],
       [ 7,  7,  3,  2],
       [ 1, 12,  3, 13]], dtype=int32)

In [182]:
v = len(tk.word_index) + 1 #oov의 인덱스
end_data = pad_sequences(ec_data,padding='post', maxlen=4, truncating='post', value=v)  #oov의 값(인덱스값)을 걍 제일 마지막 인덱스로 지정
end_data

array([[ 1,  5, 14, 14],
       [ 1,  8,  5, 14],
       [ 1,  3,  5, 14],
       [ 9,  2, 14, 14],
       [ 2,  4,  3,  2],
       [ 3,  2, 14, 14],
       [ 1,  4,  6, 14],
       [ 1,  4,  6, 14],
       [ 1,  4,  2, 14],
       [ 7,  7,  3,  2],
       [ 1, 12,  3, 13]], dtype=int32)

한국어.

In [187]:
k_data = '오늘은 시간이 빠르게 가네요'
from tensorflow.keras.preprocessing.text import Tokenizer
k_tk = Tokenizer()
k_tk.fit_on_texts([k_data]) #한 차원 올려야 단어로 나눠줌
k_tk.index_word #인덱스:단어.

{1: '오늘은', 2: '시간이', 3: '빠르게', 4: '가네요'}

In [188]:
txt = '오늘은 이상하게 피곤 하네요 그런데 시간은 느리게 가네요'
k_tk.texts_to_sequences([txt]) #있는 데이터는 미리 학습된 vocabulary에 해당하는 인덱스로 변환, 없는 단어는 사라짐

[[1, 4]]